### ISSUE TITLE
 install windows game on wine  without interactive with wine

### ISSUE THREAD

**Issue by saman-aliveisi** [1vanyk1/Awimul#1]
hi friend 
i want install windows game on wine from android command ( without interactive with wine) .
in other words the user that run app , select exe game and dont user login to wine.
app automatic install exe on wine

thanks

**Comment by 1vanyk1** [comment]
Hello. Currently I am working on other parts. I will add an option to run exact .exe file by a path to file or a shortcut when I end the current work. I think this will also help in automatic installations.
If you would like to transfer .exe files from storage onto Wine environment, I can make a file manager which can transfer files or directories.

**Comment by saman-aliveisi** [comment]
thanks bro @1vanyk1 
thats very nice so professional

**Comment by saman-aliveisi** [comment]
i have 2 questions for prevent spam i ask here , pls answer me bro , so so thanks.

1- im run demo apk and download obb in xiaomi 7 and emulator but not working and in start wines level ( load wine) stopped [long time the message load wine showing without any login to wine]

2- how to create obb file ( if  have  instruction or tutorial to make or building custom obb wine please send me)

my mail : saman.aliveisi.app@gmail.com

thanks bro

**Comment by 1vanyk1** [comment]
1. I do not really understand why it happens. Thank you for finding a problem on Xiaomi 7, because I want this emulator to be stable on most devices. I will try to fix it. Have you got logs? Have you got Android Studio on PC or Logcat Reader (or another similar application) on your phone to read logs? If you have got logs please send them me.
2. Now, I use prebuild Wine for android. [There is a good guide](https://joshumax.github.io/general/2018/01/19/building-wine-3-0-on-android.html), but there can be some problems in building. The directory, which is used for obb, is in <path to wine>/dlls/wineandroid.drv/assets. This building method is not easy, so I will try to change it. Then I will write an instruction.

**Comment by saman-aliveisi** [comment]
thanks bro for guide .
Im open the project in android studio

there are several problem :
1- the **obb folder not create** in android folder in device or emulator and i create manually (com.vantacom.aarm folder)

2- after install and downloading obb, im waiting for long time to log. the **screen loading wine crashes ** with bellow error and no login to wine ( image attach)

error : 

```
E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: com.vantacom.aarm, PID: 2777
    java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
        at androidx.fragment.app.DialogFragment.show(DialogFragment.java:277)
        at com.vantacom.aarm.MainActivity.noObb(MainActivity.java:120)
        at com.vantacom.aarm.dialogs.DownloadFilesDialog$1.run(DownloadFilesDialog.java:177)
        at java.lang.Thread.run(Thread.java:764) 
```

```
I/System.out: Loading...
E/WM: (EE)
     
    Fatal server error:
    (EE)
     
    Could not create lock file in Thread-6/.tX0-lock
    (EE)
     
E/WM: Failed to open X display :0
```

![01](https://user-images.githubusercontent.com/9861867/147392920-bae8ba11-172d-45a2-8c4a-2640b8e4f6fe.PNG)

**Comment by 1vanyk1** [comment]
1. Thank you for finding this bug. It will be fixed. [Also a prebuilt obb is here which works for me](https://drive.google.com/file/d/1NWkPi1tiYKqAoZy_p-KGw13lxaVkzxX5/view).
2. I know about this bug. I hope I have fixed it. The reason of this problem that Window Manager cannot connect x-server, because in this version if it connects he will close x-server (the bug is here) and tries to connect again, but x-server is closed so he cannot create lock file.  Also, I am glad to see that x-server works on Xiaomi. 

Well, I want to say thank you for finding all these bugs. But there is a problem. The last version **cannot** load Wine. The reason is that I am changing Wine loading process. Previous versions used Wine which is specially built for Android. The main problem is there are many limitations in Android kernel. But Android can boot in a Linux repository (by using proot or chroot) which has not got these limitations and then load Wine there. These is much harded to make but it will have better compability with more devices and you can use some more new options (for example hardware acceleration).

If you want to load Wine now you can use the [awimul.apk](https://github.com/1vanyk1/Awimul/blob/master/awimul.apk) from the root of this repository. It can load Wine and you can run some apps. I hope you will enjoy it.

**Comment by saman-aliveisi** [comment]
yeah thats great bro , thanks so much for explains.  

[ this repo is exagear decompile code ](https://github.com/khanhduytran0/exagear_windows_emulator) i think can helps to acceleration algorithm.

which version of repo can load wine ? thanks if send me the old stable version that load wine (works fine)

i want fork repo and pull new option to your repo but unfortunality cant  whith this version and i dont run.

pls send me old version **(codes)** that works fine

**Comment by 1vanyk1** [comment]
There is one main problem in ExaGear. It has not got hardware acceleration. Also without decompiled .so libs it is nearly impossible to add it. The only way is VirGL, but it does not work on most devices.
[Version Alpha 0.3.6 or d636051](https://github.com/1vanyk1/Awimul/commit/d636051fd1f57e763bb06a8a945eea4acf69bbbf) is stable and loads Wine.

**Comment by saman-aliveisi** [comment]
thanks friend .

this alpha version has problem

-- in arm abis  , code run and install but no login to wine (in loading wine the app crash and stop)

-- in x86 abis , the app not installed with error

**Installation did not succeed.
The application could not be installed: INSTALL_FAILED_NO_MATCHING_ABIS**


i checked jnilibs that arm-v7a is exist , but for x86 arm or arm 64 where and how create libs?

**Comment by saman-aliveisi** [comment]
important : **please guide**

i want create app like exagear that your repo is the best im finding.
my app is game launcher that users can download and directly start gaming without interactive with wine.

therefor i need to some option : 
*the app compatible with most devices
*the app kernel based on wine without wine inteactive

that your repo is best for my idea. if guide im so glade and refer your repo 100%.

**Comment by 1vanyk1** [comment]
Hello. I am sorry I have not replied earlier. This emulator is for ARM 32 bit devices, but it should work with ARM 64 bit. The main purpose of this project is to run Windows apps on ARM devices. But I can try to add x86 support later. Probably, x-server will run on x86 device.
If you need to run WINE on x86 device, you can rebuild libs.
